# Generated by Django 3.2.14 on 2022-07-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0019_rename_profile_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
