# Generated by Django 3.2.14 on 2022-07-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0022_rename_perfil_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
