# Generated by Django 3.2.14 on 2022-07-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0024_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
